from __future__ import annotations

from datetime import date

from pst_gate.models import Decision, Policy


def advisory_markdown(
    decision: Decision, policy: Policy, today: date | None = None
) -> str:
    today = today or date.today()
    blocking = [
        finding
        for finding in decision.findings
        if finding.status in {"block", "expired_exception"}
    ]
    accepted = [finding for finding in decision.findings if finding.status == "accepted"]
    known = [finding for finding in decision.findings if finding.status == "baseline"]
    lines = [
        "# Product security advisory (generated)",
        "",
        f"- Date: `{today.isoformat()}`",
        f"- Gate: **{decision.verdict}** (fail on {policy.fail_on}+)",
        "- This is a customer-facing *draft* from the same corpus as CI, not a CVE filing.",
        "",
        "## New or blocking this change",
        "",
    ]
    if not blocking:
        lines.append("None.")
    else:
        for finding in blocking:
            package_note = f" ({finding.package} {finding.cve})" if finding.cve else ""
            lines.append(
                f"- **{finding.severity.upper()}** {finding.owasp} — `{finding.rule_id}` "
                f"@ `{finding.path}`{package_note}. "
                f"Owner: {finding.owner}. Status: {finding.status}."
            )
    lines += ["", "## Fixed since last baseline", ""]
    if not decision.fixed_since_baseline:
        lines.append("None detected (fingerprints still present, or empty baseline).")
    else:
        for fingerprint_id in decision.fixed_since_baseline:
            lines.append(f"- `{fingerprint_id}`")
    lines += ["", "## Accepted exceptions still open", ""]
    if not accepted:
        lines.append("None.")
    else:
        for finding in accepted:
            lines.append(f"- `{finding.fingerprint}` {finding.rule_id} — {finding.owner}")
    lines += ["", "## Known (in baseline, not failing)", ""]
    lines.append(f"{len(known)} findings carried forward. They do not fail this PR.")
    if decision.sbom.get("present"):
        lines += [
            "",
            "## Supply chain",
            "",
            f"CycloneDX SBOM with **{decision.sbom.get('components')}** components "
            f"(`{decision.sbom.get('name')}`). "
            "Artifact list is an Actions artifact on the same run.",
        ]
    lines += ["", "---", "Generated by pst-gate. Review before you send this to a customer.", ""]
    return "\n".join(lines)
