from __future__ import annotations

import re
from pathlib import Path

_AI_MARKERS = re.compile(
    r"Co-authored-by:\s*Copilot|GitHub Copilot|generated by (copilot|cursor|chatgpt)|<!-- copilot",
    re.I,
)


def ai_touched_paths(diff_text: str, extra_paths: list[Path] | None = None) -> set[str]:
    """Paths whose diff hunk or file content looks AI-authored.

    Heuristic on purpose: Copilot trailers, generator comments. Used to *annotate*
    findings, not to fail the gate by itself.
    """
    touched: set[str] = set()
    current: str | None = None
    file_has_marker = False
    for line in (diff_text or "").splitlines():
        if line.startswith("diff --git "):
            if current and file_has_marker:
                touched.add(current)
            file_has_marker = False
            parts = line.split()
            current = None
            if len(parts) >= 4:
                current = parts[3][2:] if parts[3].startswith("b/") else parts[3]
            continue
        if _AI_MARKERS.search(line):
            file_has_marker = True
    if current and file_has_marker:
        touched.add(current)
    if _AI_MARKERS.search(diff_text or "") and not touched:
        for line in (diff_text or "").splitlines():
            if line.startswith("+++ b/"):
                touched.add(line[6:])
    for extra_path in extra_paths or []:
        if not extra_path.is_file():
            continue
        try:
            text = extra_path.read_text(encoding="utf-8", errors="replace")[:50_000]
        except OSError:
            continue
        if _AI_MARKERS.search(text):
            touched.add(str(extra_path).replace("\\", "/"))
    return {path.lstrip("./") for path in touched if path}


def finding_ai_touched(path: str, ai_paths: set[str]) -> bool:
    normalized = path.replace("\\", "/").lstrip("./")
    if normalized in ai_paths:
        return True
    return any(
        normalized.endswith(ai_path) or ai_path.endswith(normalized) for ai_path in ai_paths
    )
