from __future__ import annotations

import hashlib
import json
import os
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(65536)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def provenance_for_sbom(
    sbom_path: Path,
    dest: Path,
    *,
    builder_id: str = "https://github.com/VinaySobarad/pst-gate",
) -> dict[str, Any]:
    """in-toto statement pointing at the SBOM. GitHub-job provenance, not SLSA L3."""
    digest = sha256_file(sbom_path)
    statement = {
        "_type": "https://in-toto.io/Statement/v1",
        "subject": [{"name": sbom_path.name, "digest": {"sha256": digest}}],
        "predicateType": "https://slsa.dev/provenance/v1",
        "predicate": {
            "buildDefinition": {
                "buildType": "https://github.com/VinaySobarad/pst-gate/provenance@v1",
                "externalParameters": {
                    "repository": os.environ.get("GITHUB_REPOSITORY", ""),
                    "ref": os.environ.get("GITHUB_REF", ""),
                    "sha": os.environ.get("GITHUB_SHA", ""),
                },
            },
            "runDetails": {
                "builder": {"id": builder_id},
                "metadata": {
                    "invocationId": os.environ.get("GITHUB_RUN_ID", ""),
                    "startedOn": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
                },
            },
        },
        "comment": "Generated by pst-gate in GitHub Actions. Not a SLSA Build L3 attestation.",
    }
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(statement, indent=2) + "\n", encoding="utf-8")
    return statement
